config/routes.rb
Omrails::Application.routes.draw do
  resources :servs

  resources :opps

  resources :pins

  devise_for :views

  devise_for :users
  resources :users, :only => [:show]

  get 'about' => 'pages#about'
  root :to => 'pins#index'

end

app/models/opp.rb
class Opp < ActiveRecord::Base
  attr_accessible :title

  validates :title, presence: true

  belongs_to :user
  validates :user_id, presence: true
end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image 


  validates :description, presence: true 
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  						content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif']},
  						size: { less_than: 5.megabytes }

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"} 
end

app/models/serv.rb
class Serv < ActiveRecord::Base
  attr_accessible :description, :title

  validates :description, presence: true
  validates :title, presence: true

  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, # :recoverable, 
         :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name

  # attr_accessible :title, :body

  has_many :pins

  has_many :opps, :dependent => :destroy

end

app/models/view.rb
class View < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/opps_controller.rb
class OppsController < ApplicationController

  before_filter :authenticate_user!, except: [:index]


  # GET /opps/new
  # GET /opps/new.json
  def new
    @opp = current_user.opps.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @opp }
    end
  end

  # GET /opps/1/edit
  def edit
    @opp = current_user.opps.find(params[:id])
  end

  # POST /opps
  # POST /opps.json
  def create
    @opp = current_user.opps.new(params[:opp])

    respond_to do |format|
      if @opp.save
        format.html { redirect_to @opp, notice: 'Opp was successfully created.' }
        format.json { render json: @opp, status: :created, location: @opp }
      else
        format.html { render action: "new" }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /opps/1
  # PUT /opps/1.json
  def update
    @opp = current_user.opps.find(params[:id])

    respond_to do |format|
      if @opp.update_attributes(params[:opp])
        format.html { redirect_to @opp, notice: 'Opp was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @opp.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /opps/1
  # DELETE /opps/1.json
  def destroy
    @opp = current_user.opps.find(params[:id])
    @opp.destroy

    respond_to do |format|
      format.html { redirect_to opps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc")

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/servs_controller.rb
class ServsController < ApplicationController
  # GET /servs
  # GET /servs.json
  def index
    @servs = Serv.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servs }
    end
  end

  # GET /servs/1
  # GET /servs/1.json
  def show
    @serv = Serv.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @serv }
    end
  end

  # GET /servs/new
  # GET /servs/new.json
  def new
    @serv = Serv.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @serv }
    end
  end

  # GET /servs/1/edit
  def edit
    @serv = Serv.find(params[:id])
  end

  # POST /servs
  # POST /servs.json
  def create
    @serv = Serv.new(params[:serv])

    respond_to do |format|
      if @serv.save
        format.html { redirect_to @serv, notice: 'Serv was successfully created.' }
        format.json { render json: @serv, status: :created, location: @serv }
      else
        format.html { render action: "new" }
        format.json { render json: @serv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servs/1
  # PUT /servs/1.json
  def update
    @serv = Serv.find(params[:id])

    respond_to do |format|
      if @serv.update_attributes(params[:serv])
        format.html { redirect_to @serv, notice: 'Serv was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @serv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servs/1
  # DELETE /servs/1.json
  def destroy
    @serv = Serv.find(params[:id])
    @serv.destroy

    respond_to do |format|
      format.html { redirect_to servs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/opps_helper.rb
module OppsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/servs_helper.rb
module ServsHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
			<small>

					by Matthew Wachter
			</small>	
			</div>	

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "Project Rails", root_path, class: "brand" %>
      <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
      	<ul class="nav">
        	<li><%= link_to "Home", root_path %></li>
  		    <li><%= link_to "About", about_path %></li>
	     </ul>
	     <ul class="nav pull-right">
          <% if user_signed_in? %>
          <li><%= link_to "Add +", new_pin_path %></li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% else %>

      	    <li><%= link_to "Login", new_user_session_path %></li>

          <% end %>
	     </ul>
    </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-#{name}")%>
				<% end %>
			<%= yield %>
			<%= render 'layouts/footer' %>
		</div>
	</body>
</html>

app/views/opps/_form.html.erb
<%= simple_form_for(@opp, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

 <%= f.input :title, as: :text, input_html: { rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/opps/_opp.html.erb
<tr>
        <td><%= opp.title %></td>
        <td><%= link_to 'Show', opp %></td>
    <% if current_user == opp.user %>
        <td><%= link_to 'Edit', edit_opp_path(opp) %></td>
        <td><%= link_to 'Destroy', opp, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <% end %>
</tr>

app/views/opps/edit.html.erb
<h1>Editing opp</h1>

<%= render 'form' %>

<%= link_to 'Show', @opp %> |
<%= link_to 'Back', opps_path %>

app/views/opps/index.html.erb
<h1>Listing opps</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>


</table>

<br />

<%= link_to 'New Opp', new_opp_path %>

app/views/opps/new.html.erb
<h1>New opp</h1>

<%= render 'form' %>

<%= link_to 'Back', opps_path %>

app/views/opps/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
		<p>
		  <%= @opp.title %>
		</p>
		<p>
		  <%= @opp.user.name %>
		</p>

		<% if current_user == @opp.user %>
		<%= link_to 'Edit', edit_opp_path(@opp) %> |
		<% end %>
		<%= link_to 'Back', opps_path %>
		</div>
	</div>
</div> 

app/views/pages/_home.html.erb
 <% unless user_signed_in? %>

<div class="hero-unit">
	<h1>Welcome to Project Rails</h1>
	<p>You've found the homepage for Matthew Wachter's website
	</p>
	<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>
<% end %>

app/views/pages/about.html.erb
<h1>About</h1>
<p> 
	This Matthew Wachter's sample app. 
</p>

app/views/pages/home.html.erb
<% if user_signed_in? %>
 	<h1>You're logged in!</h1>
 <% else %>

<div class="hero-unit">
	<h1>Welcome to One Month Rails</h1>
	<p>You've found the homepage for the 
		<%= link_to "One Month Rails", "http://onemonthrails.com"%>
		application.
	</p>
	<p>
		<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
	</p>
</div>
<% end %>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

 <%= f.input :description, as: :text, input_html: { rows: "3"} %>


  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
    	<%= pin.description %>
	</p>
	<p>
		<strong>
			Posted by <%= pin.user %>
		</strong>	
	</p>

    <% if current_user == pin.user %>
    	<p>
	    	<%= link_to 'Edit', edit_pin_path(pin) %>
	    	<%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' } %>
		</p>
    <% end %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
		<p> 
			<%= @pin.name %>
		</p>
		<p>
		  <%= @pin.description %>
		</p>
		<p>
		  <%= @pin.user.name %>
		</p>

		<% if current_user == @pin.user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
		<%= link_to 'Back', pins_path %>
		</div>
	</div>
</div> 

app/views/servs/_form.html.erb
<%= simple_form_for(@serv, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

    <%= f.input :title, as: :text, input_html: { rows: "1"} %>
    <%= f.input :description, as: :text, input_html: { rows: "3"} %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/servs/_serv.html.erb
  <tr>
  	<td><%= serv.title %></td>
    <td><%= serv.description %></td>
    <td><%= link_to 'Show', serv %></td>
    <td><%= link_to 'Edit', edit_serv_path(serv) %></td>
    <td><%= link_to 'Destroy', serv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>

app/views/servs/edit.html.erb
<h1>Editing serv</h1>

<%= render 'form' %>

<%= link_to 'Show', @serv %> |
<%= link_to 'Back', servs_path %>

app/views/servs/index.html.erb
<h1>Listing servs</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  <thead>

<tbody>
  <%= render @servs %>
</tbody>

<%= link_to 'New Serv', new_serv_path %>

app/views/servs/new.html.erb
<h1>New serv</h1>

<%= render 'form' %>

<%= link_to 'Back', servs_path %>

app/views/servs/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
<p>
  <%= @serv.title %>
</p>
<p>
  <%= @serv.description %>
</p>

<%= link_to 'Edit', edit_serv_path(@serv) %> |
<%= link_to 'Back', servs_path %>
		</div>
	</div>
</div>		